alert('Hello,Shota!);
alert(1+1);
alert('Hello,Shota!);
alert(1+1);
alert(Math.sprt(1+1));
・２の平方根と３の平方根の和を計算しなさい。
・１を０で割るとどうなるのか、試してみなさい。
・０を０で割るとどうなるのか、試してください。
alert(2+3)
alert('2'+'3')
alert(Number('2')+Number('3'))
alert
